Remove support for PHP 8.0, Upgrade PHPUnit to 10.x
laminas/laminas-filter pull request #101
Opened 2023-05-15 20:36 UTC by gsteel

Closes #100

- Bumps Service Manager to ^3.21.0 for PHPUnit 10 Compat
- Drops support for PHP 8.0
- Upgrades PHPUnit to 10.1.x

2023-05-15 20:47 UTC, Ocramius approved these changes
Thanks @gsteel!

2023-05-15 20:47 UTC, Ocramius commented
> snappy_compress : expects parameter to be string.

Nnnnnggghhh

2023-05-15 20:52 UTC, gsteel commented
I think I'm gonna have to disable the `rar` extension and tests:
https://github.com/cataphract/php-rar/issues/17

Not sure why it was building a few weeks ago - perhaps a PHP patch release broke it.

2023-05-15 21:12 UTC, gsteel commented
Green now @Ocramius 😅

2023-05-16 08:38 UTC, Ocramius requested changes

2023-05-16 08:38 UTC, Ocramius commented on test/Compress/SnappyTest.php
> +        restore_error_handler();
This will never be reached

2023-05-16 08:41 UTC, gsteel commented on test/Compress/SnappyTest.php
> +        restore_error_handler();
🤦‍♂️

2023-05-16 23:24 UTC, Ocramius approved these changes
Thanks @gsteel

2023-05-16 23:25 UTC, merged