Add Missing `getOptions` method to `CompressionAlgorithmInterface`
laminas/laminas-filter pull request #113
Opened 2023-11-01 20:51 UTC by gsteel

|    Q          |   A
|-------------- | ------
| BC Break      | yes
| New Feature   | yes

### Description

This `getOptions` method is called on `CompressionAlgorithmInterface` as if it were `AbstractCompressionAlgorithm`, therefore it makes sense to add it to the interface.

Needs #111

2023-11-02 19:34 UTC, Ocramius requested changes

2023-11-02 19:34 UTC, Ocramius commented on src/Compress/CompressionAlgorithmInterface.php
> +    public function getOptions(string|null $option = null): mixed;
IMO `getOptions` shouldn't be part of the interface here: getting stuff from "ready to use" services is IMO bad design.

2023-11-02 20:12 UTC, gsteel commented on src/Compress/CompressionAlgorithmInterface.php
> +    public function getOptions(string|null $option = null): mixed;
OK. I'll look at it again. Perhaps in ./src calls to ...Interface::getOptions() can be refactored, the rest of it is probably tests.

2023-11-06 09:55 UTC, Ocramius approved these changes
Thanks @gsteel!

2023-11-06 12:02 UTC, merged