implement new ToString filter, added unittests for the new filter
laminas/laminas-filter pull request #188
Opened 2024-10-24 17:27 UTC by mlussi90

|    Q          |   A
|-------------- | ------
| Documentation | no
| Bugfix        | no
| BC Break      | no
| New Feature   | yes
| RFC           | no
| QA            | no

### Description

#98 Adding a ToString Filter according to the requirements from @vaclavvanik

2024-10-25 09:15 UTC, gsteel requested changes
Thanks @mlussi90 

The `ToString` filter will need to be added to the default set of filters in `FilterPluginManager` - additionally, the v2 docs will need updating 👍

2024-10-25 09:15 UTC, gsteel commented on src/ToString.php
> +class ToString extends AbstractFilter
```suggestion
final class ToString implements FilterInterface
```

2024-10-25 09:15 UTC, gsteel commented on src/ToString.php
> +    public function filter($value): mixed
```suggestion
     * @return ($value is scalar ? string : mixed)
     */
    public function filter(mixed $value): mixed
```

2024-10-25 09:15 UTC, gsteel commented on src/ToString.php
> +    }
```suggestion
    }
    
    public function __invoke(mixed $value): mixed
    {
        return $this->filter($value);
    }
```

2024-10-25 09:15 UTC, gsteel commented on test/ToStringTest.php
> +    /** @return list<array{0: mixed}> */
```suggestion
    /** @return list<array{0: mixed, 1: string}> */
```

2024-10-25 09:15 UTC, gsteel commented on src/ToString.php
> +        if (! is_scalar($value)) {
This condition should include `Stringable`

2024-10-25 09:15 UTC, gsteel commented on test/ToStringTest.php
> +    public static function returnBasicDataProvider(): array
Data providers always appear as unused by Psalm when only referenced by the `DataProvider` attribute.

Once all other psalm issues are fixed, these 'PossiblyUnusedMethod' issues can be added to the baseline with `psalm --set-baseline=psalm-baseline.xml`

2024-10-25 09:15 UTC, gsteel commented on test/ToStringTest.php
> +<?php
Will also need a test to cover added `__invoke` method and data provider cases covering `Stringable` objects

2024-10-31 17:00 UTC, mlussi90 commented
i tried to implement all your requested changes, can you take a look?

2024-10-31 17:17 UTC, gsteel requested changes
Thanks @mlussi90 - Nearly there…

You can fix coding style problems by running `vendor/bin/phpcbf` and psalm issues with the tests can be silenced with `vendor/bin/psalm --set-baseline=psalm-baseline.xml`

2024-10-31 17:17 UTC, gsteel commented on src/FilterPluginManager.php
> +        'String' => ToString::class,
I'd rather not see any new aliases please - It's better that users get into the habit of referring to filters by the FQCN, i.e. `\Laminas\Filter\ToString::class`

2024-10-31 17:17 UTC, gsteel commented on src/FilterPluginManager.php
> +        'ToString'                   => ToString::class,
Same comment about aliases here too. Please remove.

2024-10-31 17:17 UTC, gsteel commented on src/FilterPluginManager.php
> +        ToString::class                    => InvokableFactory::class,
This should be all we need 👍

2024-10-31 17:17 UTC, gsteel commented on test/ToStringTest.php
> +        self::assertSame($output, $filter($input));
```suggestion
        self::assertSame($output, $filter->__invoke($input));
```

Sorry - a bit nit picky, but explicitly calling `__invoke` will ensure that the call cannot be interpreted any other way.

2024-10-31 20:40 UTC, gsteel requested changes
Thank you @mlussi90 

In order to get CI green for Psalm, you'll need to refresh the baseline - this sort of thing can happen, particularly on Mac, so it's not your fault!

Try running `vendor/bin/psalm --update-baseline --no-cache --threads=1` and verify there are no more problems with `vendor/bin/psalm --no-cache --threads=1`, then commit the altered baseline.

The BC check failure can be ignored - it's complaining about the altered default value for plugin manager factories.

2024-10-31 20:59 UTC, mlussi90 commented
@gsteel thank you very much for your help, the checks are looking better now i think

2024-10-31 21:07 UTC, gsteel approved these changes
Thanks @mlussi90 

I'll merge and release shortly, once I've got the docs organised 👍

2024-10-31 21:18 UTC, merged