Apply one line per sentence style to md files
laminas/laminas-filter pull request #199
Opened 2024-11-15 16:03 UTC by ramchale

|    Q          |   A
|-------------- | ------
| Documentation | yes
| Bugfix        | no
| BC Break      | no
| New Feature   | no
| RFC           | no
| QA            | no

### Description

Apply one line per sentence style to md files. 

As this is the desired standard going forward, applying this to existing files will make it easier to adopt.

2024-11-15 17:42 UTC, gsteel requested changes
Thanks @ramchale - I found only 1 problem 👍

2024-11-15 17:42 UTC, gsteel commented on docs/book/v2/inflector.md
> +```php class Foo
```suggestion
```php
class Foo
```

2024-11-15 17:50 UTC, gsteel commented
FYI, I drop this `Makefile` into my local Laminas repos so that you can easily build the docs website with `make docs` and open `./docs/html/index.html` in your browser

[Makefile.txt](https://github.com/user-attachments/files/17779111/Makefile.txt)

2024-11-16 08:55 UTC, ramchale commented on docs/book/v2/inflector.md
> +```php class Foo
Awesome. Thanks
I've amended that

2024-11-18 22:58 UTC, froschdesign approved these changes
LGTM 👍🏻

2024-11-19 09:11 UTC, merged