Refactor RenameTest
laminas/laminas-filter pull request #212
Opened 2024-12-21 13:36 UTC by ramchale

- Only remove temp directory after all tests have run
- Use DataProvider for filter config and input variations

|    Q          |   A
|-------------- | ------
| Documentation | no
| Bugfix        | no
| BC Break      | no
| New Feature   | no
| RFC           | no
| QA            | yes

### Description

Draft PR to discuss refactoring of RenameTest.

Started looking at this as part of the moving the Rename filter to v3, but this feels like a big enough piece of refactoring in itself to be worth sense checking.

As DataProviders run before any of the test hooks, the creation of the tmp test file is moved to a static method that creates it on first use, and then it's not removed until all the tests in RenameTest have run. Likewise for the sub directory needed for testing moving a file to a target directory.

The cleanup for the indvidual files created by tests has been moved to each test. Could potentially be moved back to tearDown if we're not concerned about the number of redundant calls, and depending on what seems more readable.

2025-01-03 23:21 UTC, gsteel requested changes
Thanks @ramchale
This test was a real mess huh? LGTM, other than one item.
Hopefully we've got enough in the current 2.x release branch to tag and merge this up into 3.x when its ready 👍

2025-01-03 23:21 UTC, gsteel commented on test/File/RenameTest.php
> +    /** @param FilterInput $expectedFilterResult **/
The `FilterInput` parameter type isn't imported anywhere AFAICT

2025-01-06 12:04 UTC, ramchale commented on test/File/RenameTest.php
> +    /** @param FilterInput $expectedFilterResult **/
Thanks

2025-01-06 12:09 UTC, ramchale commented
> Thanks @ramchale This test was a real mess huh? LGTM, other than one item. Hopefully we've got enough in the current 2.x release branch to tag and merge this up into 3.x when its ready 👍

Happy New Year!
Unit testing anything involving the file system is always a pain 😓
Thanks. That should be updated now

2025-01-06 15:27 UTC, gsteel approved these changes
Thank you @ramchale :)

2025-01-06 15:27 UTC, merged