Filter for arithmetic operations #28
laminas/laminas-filter pull request #29
Opened 2021-07-13 20:03 UTC by fgsl

### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | no
| BC Break    | no

#### Summary

I created this filter for an application that converts values from APIs. It's useful for measure unit conversions and making adjustments. For example, an endpoint returns the amount of RAM requested by an user and you can add a security margin.

2021-07-14 12:42 UTC, boesing commented
No worries, there is no way to let you fix the codestyle.
Ignore it for now, its a known issue with running coding-standard v1 on PHP 7.4.

2021-07-14 12:48 UTC, fgsl commented
> No worries, there is no way to let you fix the codestyle.
> Ignore it for now, its a known issue with running coding-standard v1 on PHP 7.4.

Thank you and excuse me. I thought I must format the code again and sent a new change...

2021-07-15 08:20 UTC, froschdesign requested changes
We definitely need some documentation that shows real use cases for this filter.

2021-07-15 08:20 UTC, froschdesign commented on src/FourOperations.php
> +        }
Please allow a creation of the filter without options, this would be consistent with other filters and their behaviour in the current version. Setter and getters are needed then, also the related unit tests.
Compare with the `PrepReplace` filter:

https://github.com/laminas/laminas-filter/blob/2c5e0f440bfd0de8e4c09e28269249a8785f1185/src/PregReplace.php#L121-L135

2021-07-15 08:20 UTC, froschdesign commented on src/FourOperations.php
> +class FourOperations extends AbstractFilter
The _four_ operations are addition, subtraction, multiplication and division but here we have one more.

2021-07-15 08:20 UTC, froschdesign commented on test/FourOperationsTest.php
> +    public function testOperations(): void
A [data provider](https://phpunit.readthedocs.io/en/9.5/writing-tests-for-phpunit.html#data-providers) can be used here.

2021-07-15 08:20 UTC, froschdesign commented on test/FourOperationsTest.php
> +class FourOperationsTest extends TestCase
Please test also invalid data types.

2021-07-15 12:53 UTC, fgsl commented on src/FourOperations.php
> +        }
Done!

2021-07-15 12:53 UTC, fgsl commented on src/FourOperations.php
> +class FourOperations extends AbstractFilter
Done!

2021-07-15 12:53 UTC, fgsl commented on test/FourOperationsTest.php
> +    public function testOperations(): void
Done!

2021-07-15 12:53 UTC, fgsl commented on test/FourOperationsTest.php
> +class FourOperationsTest extends TestCase
Done!

2021-07-15 16:47 UTC, fgsl commented
I made a little change on typing, but I don't know I had to follow all the messages in https://github.com/laminas/laminas-filter/actions/runs/1033956242. I think some parameters must be mixed, because they can be integers or floats.

2021-10-24 21:02 UTC, Ocramius requested changes

2021-10-24 21:02 UTC, Ocramius commented on src/FiveOperations.php
> +class FiveOperations extends AbstractFilter
IMO worth having separate filters, than one named "five operations" that merges them all together: having one thing that does multiple separate things is at the root of most accidental complexity in software.

2021-10-25 14:50 UTC, fgsl commented
Hi, @Ocramius. I have splitted the new filter into five filters, according your guideline.

2021-12-02 13:54 UTC, weierophinney requested changes
First, this needs to be rebased against the current release branch (currently 2.13.x, but likely to become 2.14.x later today when the PHP 8.1 support is merged); there are a few artifacts in here that seem to be from already merged changes (specifically the `AllowList` and `DenyList` implementations and tests). 

Second, I've noted a number of areas where the behavior of the filters would not behave as expected when using integer values and operands. These likely need to be split into additional filters to allow both integer and float operations (with the exception of the `Div` filter, where a float is always expected).

2021-12-02 13:54 UTC, weierophinney commented on src/Add.php
> +        $operand = (float) $this->options['operand'];
Why the cast to float here?

If I were operating on integers, I'd expect an integer return value. Perhaps this should be broken into "AddInteger" and "AddFloat"?

2021-12-02 13:54 UTC, weierophinney commented on src/Sub.php
> +        $operand = (float) $this->options['operand'];
Same remark as for the `Add` filter; should this maybe be broken into `SubInt` and `SubFloat`?

2021-12-02 13:54 UTC, weierophinney commented on src/Mod.php
> +        return ($value % $operand);
This doesn't do what you think it does. From the manual:

> Operands of modulo are converted to int before processing. For floating-point modulo, see fmod().

In other words, using the `%` operator will always return an integer. If you want to work with floats, you need to use `fmod()`. So, perhaps two variants, `Mod` and `FloatMod`, are needed.

2021-12-02 13:54 UTC, weierophinney commented on src/Mul.php
> +        return ($value * $operand);
Same remark as for `Add` and `Sub`: if integers are used, I'd expect an integer return value, not casting to float.

2025-04-11 10:33 UTC, closed without merging

2025-04-11 10:33 UTC, gsteel commented
As this patch is getting on for 4 years old, and looks abandoned - I'm closing for now. Feel free to send in another patch, but please bear in mind that v3 is close to release with some significant changes.